import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsProvider } from "@/contexts/ProductsContext";
import { LocationsProvider } from "@/contexts/LocationsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-black dark:text-white">
      <body className={inter.className}>
        <ProductsProvider>
          <LocationsProvider>
            {children}
          </LocationsProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
